[package]
name = "cdk-spark"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
async-trait.workspace = true
anyhow.workspace = true
cdk-common.workspace = true
futures.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
lightning-invoice.workspace = true
lightning.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
bip39.workspace = true
bitcoin.workspace = true
async-stream = "0.3"

# Spark SDK dependencies
spark-wallet = { path = "../../../spark-sdk/crates/spark-wallet" }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }

