/// @generated
/// Auto-generated by build.rs
pub static MIGRATIONS: &[(&str, &str, &str)] = &[(
    "",
    "001_create_ldk_kv_store.sql",
    include_str!(r#"./migrations/001_create_ldk_kv_store.sql"#),
)];
