coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  unit:
    paths:
      - "crates/**"
      - "!crates/cdk-integration-tests/**"
  integration:
    paths:
      - "crates/cdk-integration-tests/**"

ignore:
  - "fuzz/**"
  - "examples/**"
  - "misc/**"
  - "**/migrations/**"
  - "**/tests/**"
