-- Widen only the columns whose value can outgrow a signed 32-bit one. Amounts
-- are u64 with no cap, a unix timestamp in int4 stops working in 2038, and
-- melt_quote's estimated_blocks and selected_fee_index are u32 values the
-- payment backend assigns, so they get the same width as the wallet columns
-- that mirror them.
--
-- The integer columns left out of this file are produced locally and bounded
-- by construction: keyset.derivation_path_index is a rotation counter,
-- blind_signature.order_index indexes one request's outputs, keyset_epoch.id
-- is always zero, and the two serial ids are generated by the database and
-- never bound. The driver refuses a value an int4 column cannot hold instead
-- of truncating it, so those stay as they are.
--
-- Each ALTER rewrites the table under an ACCESS EXCLUSIVE lock; the
-- operational cost is measured in docs/migrations/v0.18.md.

ALTER TABLE melt_quote
    ALTER COLUMN amount TYPE BIGINT,
    ALTER COLUMN fee_reserve TYPE BIGINT,
    ALTER COLUMN expiry TYPE BIGINT,
    ALTER COLUMN created_time TYPE BIGINT,
    ALTER COLUMN paid_time TYPE BIGINT,
    ALTER COLUMN estimated_blocks TYPE BIGINT,
    ALTER COLUMN selected_fee_index TYPE BIGINT;

ALTER TABLE melt_request
    ALTER COLUMN inputs_amount TYPE BIGINT,
    ALTER COLUMN inputs_fee TYPE BIGINT;

ALTER TABLE proof
    ALTER COLUMN amount TYPE BIGINT,
    ALTER COLUMN created_time TYPE BIGINT;

ALTER TABLE blind_signature
    ALTER COLUMN amount TYPE BIGINT,
    ALTER COLUMN created_time TYPE BIGINT,
    ALTER COLUMN signed_time TYPE BIGINT;

ALTER TABLE mint_quote
    ALTER COLUMN amount TYPE BIGINT,
    ALTER COLUMN expiry TYPE BIGINT,
    ALTER COLUMN created_time TYPE BIGINT,
    ALTER COLUMN amount_paid TYPE BIGINT,
    ALTER COLUMN amount_issued TYPE BIGINT;

ALTER TABLE mint_quote_payments
    ALTER COLUMN timestamp TYPE BIGINT,
    ALTER COLUMN amount TYPE BIGINT;

ALTER TABLE mint_quote_issued
    ALTER COLUMN amount TYPE BIGINT,
    ALTER COLUMN timestamp TYPE BIGINT;
