-- Every column holding a value the mint does not control gets a type wide
-- enough for it.
--
-- Amounts are u64 on the wire, and int8 covers all but the top half of that
-- range, so a peer could name an amount the mint had to refuse rather than
-- store. They become numeric(20, 0), which holds every u64; the driver refuses
-- a value read back that is negative, fractional or wider.
--
-- Everything else that had outgrown int4 becomes int8: a unix timestamp in int4
-- stops working in 2038, keyset's valid_from, valid_to and input_fee_ppk are
-- u64 in Rust, and melt_quote's estimated_blocks and selected_fee_index are u32
-- values the payment backend assigns. int4 wrapped anything above 2^31 into a
-- negative row that the checked read path then rejected, which failed every
-- read of the table rather than only its own row. These stay integers because a
-- clock cannot reach the signed maximum and their ordering and arithmetic are
-- then native.
--
-- The integer columns left out of this file are produced locally and bounded by
-- construction: keyset.derivation_path_index is a rotation counter,
-- blind_signature.order_index indexes one request's outputs, keyset_epoch.id is
-- always zero, and the two serial ids are generated by the database and never
-- bound. The driver refuses a value an int4 column cannot hold instead of
-- truncating it, so those stay as they are.
--
-- u64_add and u64_sum exist so one statement works on both backends. Here they
-- are aliases of arithmetic postgres already does exactly; SQLite has no
-- unsigned type and promotes an integer overflow to a float, so it implements
-- them in rust and this side matches their names.
--
-- What refuses an out of range total on this side is the check constraint on
-- keyset_amounts, since numeric(20, 0) on its own admits about five times
-- u64::MAX.
--
-- Each ALTER rewrites the table under an ACCESS EXCLUSIVE lock, so every column
-- of a table changes in one statement and no table is rewritten twice.

-- u64 is the conversion into the representation an amount column holds. SQLite
-- stores one as a blob, so a value SQL names rather than binds has to be
-- encoded before it can be compared against a column; here the column already
-- holds a number and the conversion is the identity. It exists so a statement
-- comparing an amount is written once and runs on either backend.
CREATE OR REPLACE FUNCTION u64(a NUMERIC) RETURNS NUMERIC
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
    AS $$ SELECT a $$;

CREATE OR REPLACE FUNCTION u64_add(a NUMERIC, b NUMERIC) RETURNS NUMERIC
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
    AS $$ SELECT a + b $$;

-- numeric_add is the strict function behind the numeric + operator, so the
-- aggregate skips NULL rows the way SUM does. The initial condition makes no
-- rows total to zero rather than NULL, which is what every caller wants and
-- what the SQLite implementation returns. The combine function is what keeps a
-- large scan parallelizable.
DROP AGGREGATE IF EXISTS u64_sum(NUMERIC);
CREATE AGGREGATE u64_sum(NUMERIC) (
    SFUNC = numeric_add,
    STYPE = NUMERIC,
    COMBINEFUNC = numeric_add,
    INITCOND = '0',
    PARALLEL = SAFE
);

ALTER TABLE keyset
    ALTER COLUMN valid_from TYPE BIGINT,
    ALTER COLUMN valid_to TYPE BIGINT,
    ALTER COLUMN input_fee_ppk TYPE BIGINT;

ALTER TABLE melt_quote
    ALTER COLUMN amount TYPE NUMERIC(20, 0),
    ALTER COLUMN fee_reserve TYPE NUMERIC(20, 0),
    ALTER COLUMN expiry TYPE BIGINT,
    ALTER COLUMN created_time TYPE BIGINT,
    ALTER COLUMN paid_time TYPE BIGINT,
    ALTER COLUMN estimated_blocks TYPE BIGINT,
    ALTER COLUMN selected_fee_index TYPE BIGINT;

ALTER TABLE melt_request
    ALTER COLUMN inputs_amount TYPE NUMERIC(20, 0),
    ALTER COLUMN inputs_fee TYPE NUMERIC(20, 0);

ALTER TABLE proof
    ALTER COLUMN amount TYPE NUMERIC(20, 0),
    ALTER COLUMN created_time TYPE BIGINT;

ALTER TABLE blind_signature
    ALTER COLUMN amount TYPE NUMERIC(20, 0),
    ALTER COLUMN created_time TYPE BIGINT,
    ALTER COLUMN signed_time TYPE BIGINT;

ALTER TABLE mint_quote
    ALTER COLUMN amount TYPE NUMERIC(20, 0),
    ALTER COLUMN amount_paid TYPE NUMERIC(20, 0),
    ALTER COLUMN amount_issued TYPE NUMERIC(20, 0),
    ALTER COLUMN expiry TYPE BIGINT,
    ALTER COLUMN created_time TYPE BIGINT;

ALTER TABLE mint_quote_payments
    ALTER COLUMN amount TYPE NUMERIC(20, 0),
    ALTER COLUMN timestamp TYPE BIGINT;

ALTER TABLE mint_quote_issued
    ALTER COLUMN amount TYPE NUMERIC(20, 0),
    ALTER COLUMN timestamp TYPE BIGINT;

-- The only amount columns the server computes rather than binds. Every other
-- one arrives as a u64 that cannot be out of range by construction, so this is
-- the one place a running total needs a bound. The type change already rewrites
-- the table, so validating the constraint costs nothing extra.
ALTER TABLE keyset_amounts
    ALTER COLUMN total_issued TYPE NUMERIC(20, 0),
    ALTER COLUMN total_redeemed TYPE NUMERIC(20, 0),
    ALTER COLUMN fee_collected TYPE NUMERIC(20, 0);

ALTER TABLE keyset_amounts
    ADD CONSTRAINT keyset_amounts_u64_range
    CHECK (total_issued   BETWEEN 0 AND 18446744073709551615
       AND total_redeemed BETWEEN 0 AND 18446744073709551615
       AND fee_collected  BETWEEN 0 AND 18446744073709551615);

ALTER TABLE completed_operations
    ALTER COLUMN total_issued TYPE NUMERIC(20, 0),
    ALTER COLUMN total_redeemed TYPE NUMERIC(20, 0),
    ALTER COLUMN fee_collected TYPE NUMERIC(20, 0),
    ALTER COLUMN payment_amount TYPE NUMERIC(20, 0),
    ALTER COLUMN payment_fee TYPE NUMERIC(20, 0);
