[package]
name = "ohttp-gateway"
version = "0.1.0"
authors = ["Dan Gould <d@ngould.dev>"]
description = "A generic OHTTP gateway that forwards requests to a configured backend without storing data"
repository = "https://github.com/payjoin/rust-payjoin"
readme = "README.md"
keywords = ["bip78", "bip77", "payjoin", "bitcoin", "ohttp"]
categories = ["cryptography::cryptocurrencies", "network-programming"]
license = "MITNFA"
edition = "2021"
rust-version = "1.85"

[[bin]]
name = "ohttp-gateway"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0.99"
axum = { workspace = true, features = ["tokio"] }
base64 = "0.22.1"
bitcoin = { version = "0.32.7", features = ["base64", "rand-std"] }
bhttp = { version = "0.6.1", features = ["http"] }
bytes = "1.9.0"
clap = { workspace = true, features = ["derive", "env"] }
futures = "0.3.31"
home = "0.5.5"
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["http1", "client"] }
hyper-util = { version = "0.1.16", features = ["client", "client-legacy", "tokio"] }
reqwest = { version = "0.12.12", default-features = false, features = ["json", "rustls-tls"] }
ohttp = { package = "bitcoin-ohttp", version = "0.6.0" }
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1.47.1", features = ["full"] }
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
