[package]
name = "ohttp-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
description = "A generic OHTTP gateway that forwards requests to a configured backend without storing data"
keywords = ["bitcoin", "e-cash", "cashu", "ohttp"]
categories = ["cryptography::cryptocurrencies", "network-programming"]

[[bin]]
name = "ohttp-gateway"
path = "src/bin/main.rs"

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["tokio"] }
base64 = "0.22.1"
bitcoin.workspace = true
bhttp = { version = "0.6.1", features = ["http"] }
bytes = "1.9.0"
clap = { workspace = true, features = ["derive", "env"] }
futures.workspace = true
home.workspace = true
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["http1", "client"] }
hyper-util = { version = "0.1.16", features = ["client", "client-legacy", "tokio"] }
reqwest.workspace = true
ohttp = { package = "bitcoin-ohttp", version = "0.6.0" }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
