-- A mint URL is a mutable attribute of a mint, not its identity. Keying every
-- table on the URL meant a mint that moves (NUT-06 `urls`) had to have each of
-- those tables rewritten, and any table missed left rows stranded under the old
-- URL. Tables now reference an internal mint id that never changes, so moving a
-- mint is a single UPDATE on `mint`.

-- Rows could reference a mint URL that was never added to `mint`. Give those a
-- mint row so nothing is stranded once the reference becomes an id.
INSERT INTO mint (mint_url)
SELECT mint_url FROM (
    SELECT mint_url FROM keyset
    UNION SELECT mint_url FROM proof
    UNION SELECT mint_url FROM mint_quote
    UNION SELECT mint_url FROM melt_quote WHERE mint_url IS NOT NULL
    UNION SELECT mint_url FROM transactions
    UNION SELECT mint_url FROM wallet_sagas
) AS referenced
WHERE mint_url NOT IN (SELECT mint_url FROM mint);

ALTER TABLE mint ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE keyset DROP CONSTRAINT IF EXISTS keyset_mint_url_fkey;
ALTER TABLE mint DROP CONSTRAINT mint_pkey;
ALTER TABLE mint ADD PRIMARY KEY (id);
ALTER TABLE mint ALTER COLUMN mint_url SET NOT NULL;
ALTER TABLE mint ADD CONSTRAINT mint_mint_url_key UNIQUE (mint_url);

ALTER TABLE keyset ADD COLUMN mint_id BIGINT;
UPDATE keyset SET mint_id = mint.id FROM mint WHERE mint.mint_url = keyset.mint_url;
ALTER TABLE keyset ALTER COLUMN mint_id SET NOT NULL;
ALTER TABLE keyset DROP COLUMN mint_url;
ALTER TABLE keyset ADD CONSTRAINT keyset_mint_id_fkey
    FOREIGN KEY (mint_id) REFERENCES mint(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS keyset_mint_id_index ON keyset(mint_id);

ALTER TABLE proof ADD COLUMN mint_id BIGINT;
UPDATE proof SET mint_id = mint.id FROM mint WHERE mint.mint_url = proof.mint_url;
ALTER TABLE proof ALTER COLUMN mint_id SET NOT NULL;
ALTER TABLE proof DROP COLUMN mint_url;
ALTER TABLE proof ADD CONSTRAINT proof_mint_id_fkey
    FOREIGN KEY (mint_id) REFERENCES mint(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS proof_mint_id_index ON proof(mint_id);

ALTER TABLE mint_quote ADD COLUMN mint_id BIGINT;
UPDATE mint_quote SET mint_id = mint.id FROM mint WHERE mint.mint_url = mint_quote.mint_url;
ALTER TABLE mint_quote ALTER COLUMN mint_id SET NOT NULL;
ALTER TABLE mint_quote DROP COLUMN mint_url;
ALTER TABLE mint_quote ADD CONSTRAINT mint_quote_mint_id_fkey
    FOREIGN KEY (mint_id) REFERENCES mint(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS mint_quote_mint_id_index ON mint_quote(mint_id);

ALTER TABLE melt_quote ADD COLUMN mint_id BIGINT;
UPDATE melt_quote SET mint_id = mint.id FROM mint WHERE mint.mint_url = melt_quote.mint_url;
ALTER TABLE melt_quote DROP COLUMN mint_url;
ALTER TABLE melt_quote ADD CONSTRAINT melt_quote_mint_id_fkey
    FOREIGN KEY (mint_id) REFERENCES mint(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS melt_quote_mint_id_index ON melt_quote(mint_id);

ALTER TABLE transactions ADD COLUMN mint_id BIGINT;
UPDATE transactions SET mint_id = mint.id FROM mint WHERE mint.mint_url = transactions.mint_url;
ALTER TABLE transactions ALTER COLUMN mint_id SET NOT NULL;
DROP INDEX IF EXISTS mint_url_index;
ALTER TABLE transactions DROP COLUMN mint_url;
ALTER TABLE transactions ADD CONSTRAINT transactions_mint_id_fkey
    FOREIGN KEY (mint_id) REFERENCES mint(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS transactions_mint_id_index ON transactions(mint_id);

ALTER TABLE wallet_sagas ADD COLUMN mint_id BIGINT;
UPDATE wallet_sagas SET mint_id = mint.id FROM mint WHERE mint.mint_url = wallet_sagas.mint_url;
ALTER TABLE wallet_sagas ALTER COLUMN mint_id SET NOT NULL;
DROP INDEX IF EXISTS wallet_sagas_mint_url_index;
ALTER TABLE wallet_sagas DROP COLUMN mint_url;
ALTER TABLE wallet_sagas ADD CONSTRAINT wallet_sagas_mint_id_fkey
    FOREIGN KEY (mint_id) REFERENCES mint(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS wallet_sagas_mint_id_index ON wallet_sagas(mint_id);
