name: cdk_example_wallet
description: Simple Cashu wallet using CDK Dart bindings

environment:
  sdk: "^3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cdk:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
