use crate::database::DatabaseExecutor;
use crate::stmt::query;

/// Migrates the migration generated by `build.rs`
#[inline(always)]
pub async fn migrate<C: DatabaseExecutor>(
    conn: &C,
    migrations: &[(&str, &str)],
) -> Result<(), cdk_common::database::Error> {
    query(
        r#"
           CREATE TABLE IF NOT EXISTS migrations (
               name TEXT PRIMARY KEY,
               applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
           )
           "#,
    )
    .execute(conn)
    .await?;

    /*if query(
        r#"select count(*) from sqlite_master where name = '_sqlx_migrations'"#,
        [],
        |row| row.get::<_, i32>(0),
    )? == 1
    {
        tx.execute_batch(
            r#"
        INSERT INTO migrations
        SELECT
            version || '_' ||  REPLACE(description, ' ', '_') || '.sql',
            execution_time
        FROM _sqlx_migrations;
        DROP TABLE _sqlx_migrations;
        "#,
        )?;
    }*/

    // Apply each migration if it hasn’t been applied yet
    for (name, sql) in migrations {
        let is_missing = query("SELECT name FROM migrations WHERE name = :name")
            .bind(":name", name)
            .pluck(conn)
            .await?
            .is_none();

        if is_missing {
            query(sql).batch(conn).await?;
            query(r#"INSERT INTO migrations (name) VALUES (:name)"#)
                .bind(":name", name)
                .execute(conn)
                .await?;
        }
    }

    Ok(())
}
