use std::fmt::Debug;
use std::future::Future;
use std::time::Instant;

use cdk_common::database::Error;

use crate::database::DatabaseExecutor;
use crate::stmt::query;

const SLOW_QUERY_THRESHOLD_MS: u128 = 20;

/// A SQL database migration embedded in the application.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Migration {
    prefix: &'static str,
    name: &'static str,
    up: &'static str,
    down: Option<&'static str>,
}

impl Migration {
    /// Creates an embedded migration.
    pub const fn new(
        prefix: &'static str,
        name: &'static str,
        up: &'static str,
        down: Option<&'static str>,
    ) -> Self {
        Self {
            prefix,
            name,
            up,
            down,
        }
    }

    /// Returns the migration file name stored in the migration history table.
    pub const fn name(&self) -> &'static str {
        self.name
    }

    /// Returns whether this migration has a backward migration.
    pub const fn is_reversible(&self) -> bool {
        self.down.is_some()
    }

    fn applies_to(&self, db_prefix: &str) -> bool {
        self.prefix.is_empty() || self.prefix == db_prefix
    }
}

/// Error produced while planning a backward database migration.
#[derive(Debug, thiserror::Error)]
pub enum MigrationError {
    /// Fewer applied migrations exist than the requested rollback count.
    #[error(
        "cannot roll back {requested} migration(s): only {available} applied migration(s) are known to this binary"
    )]
    NotEnoughAppliedMigrations {
        /// Number of migrations requested by the operator.
        requested: usize,
        /// Number of applicable migrations currently recorded as applied.
        available: usize,
    },
    /// A selected migration has no paired `.down.sql` file.
    #[error(
        "migration `{name}` cannot be rolled back because it has no paired `.down.sql` migration"
    )]
    MissingDownMigration {
        /// Name of the irreversible migration.
        name: &'static str,
    },
}

fn migration_error(error: MigrationError) -> Error {
    Error::Database(Box::new(error))
}

/// Run a database operation and log slow operations, it also converts and logs any error with a
/// given info for more context. This function is expecting a synchronous database operation
#[inline(always)]
pub fn run_db_operation_sync<F, E, E1, T>(
    info: &str,
    operation: F,
    error_map: E,
) -> Result<T, Error>
where
    F: FnOnce() -> Result<T, E1>,
    E1: Debug,
    E: FnOnce(E1) -> Error,
{
    let start = Instant::now();

    tracing::trace!("Running db operation {}", info);

    let result = operation().map_err(|e| {
        tracing::error!("Query {} failed with error {:?}", info, e);
        error_map(e)
    });

    let duration = start.elapsed();
    if duration.as_millis() > SLOW_QUERY_THRESHOLD_MS {
        tracing::warn!("[SLOW QUERY] Took {} ms: {}", duration.as_millis(), info);
    }

    result
}

/// Run a database operation and log slow operations, it also converts and logs any error with a
/// given info for more context
#[inline(always)]
pub async fn run_db_operation<Fut, E, E1, T>(
    info: &str,
    operation: Fut,
    error_map: E,
) -> Result<T, Error>
where
    Fut: Future<Output = Result<T, E1>>,
    E1: Debug,
    E: FnOnce(E1) -> Error,
{
    let start = Instant::now();

    tracing::trace!("Running db operation {}", info);

    let result = operation.await.map_err(|e| {
        tracing::error!("Query {} failed with error {:?}", info, e);
        error_map(e)
    });

    let duration = start.elapsed();
    if duration.as_millis() > SLOW_QUERY_THRESHOLD_MS {
        tracing::warn!("[SLOW QUERY] Took {} ms: {}", duration.as_millis(), info);
    }

    result
}

/// Migrates the migration generated by `build.rs`
#[inline(always)]
pub async fn migrate<C>(conn: &C, db_prefix: &str, migrations: &[Migration]) -> Result<(), Error>
where
    C: DatabaseExecutor,
{
    query(
        r#"
           CREATE TABLE IF NOT EXISTS migrations (
               name TEXT PRIMARY KEY,
               applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
           )
           "#,
    )?
    .execute(conn)
    .await?;

    // Apply each migration if it hasn’t been applied yet
    for migration in migrations {
        if !migration.applies_to(db_prefix) {
            continue;
        }

        let is_missing = query("SELECT name FROM migrations WHERE name = :name")?
            .bind("name", migration.name)
            .pluck(conn)
            .await?
            .is_none();

        if is_missing {
            query(migration.up)?.batch(conn).await?;
            query(r#"INSERT INTO migrations (name) VALUES (:name)"#)?
                .bind("name", migration.name)
                .execute(conn)
                .await?;
        }
    }

    Ok(())
}

/// Rolls back the most recently applied migrations known to this binary.
///
/// The caller is responsible for wrapping this operation in a transaction. The
/// complete rollback is validated before any backward SQL is executed, so a
/// request that reaches a migration without a paired `.down.sql` file fails
/// without making changes.
#[inline(always)]
pub async fn rollback_migrations<C>(
    conn: &C,
    db_prefix: &str,
    migrations: &[Migration],
    steps: usize,
) -> Result<Vec<String>, Error>
where
    C: DatabaseExecutor,
{
    if steps == 0 {
        return Ok(Vec::new());
    }

    let mut applied = Vec::new();
    for migration in migrations
        .iter()
        .rev()
        .filter(|migration| migration.applies_to(db_prefix))
    {
        let is_applied = query("SELECT name FROM migrations WHERE name = :name")?
            .bind("name", migration.name)
            .pluck(conn)
            .await?
            .is_some();

        if is_applied {
            applied.push(migration);
        }
    }

    if applied.len() < steps {
        return Err(migration_error(
            MigrationError::NotEnoughAppliedMigrations {
                requested: steps,
                available: applied.len(),
            },
        ));
    }

    let selected = &applied[..steps];
    for migration in selected {
        if migration.down.is_none() {
            return Err(migration_error(MigrationError::MissingDownMigration {
                name: migration.name,
            }));
        }
    }

    let mut rolled_back = Vec::with_capacity(steps);
    for migration in selected {
        let down = migration.down.ok_or_else(|| {
            migration_error(MigrationError::MissingDownMigration {
                name: migration.name,
            })
        })?;
        query(down)?.batch(conn).await?;
        query("DELETE FROM migrations WHERE name = :name")?
            .bind("name", migration.name)
            .execute(conn)
            .await?;
        rolled_back.push(migration.name.to_owned());
    }

    Ok(rolled_back)
}
