use std::fmt::Debug;
use std::future::Future;
use std::time::Instant;

use cdk_common::database::Error;

use crate::database::DatabaseExecutor;
use crate::migration::{RegisteredRustMigration, RustMigration};
use crate::stmt::query;

const SLOW_QUERY_THRESHOLD_MS: u128 = 20;

/// Run a database operation and log slow operations, it also converts and logs any error with a
/// given info for more context. This function is expecting a synchronous database operation
#[inline(always)]
pub fn run_db_operation_sync<F, E, E1, T>(
    info: &str,
    operation: F,
    error_map: E,
) -> Result<T, Error>
where
    F: FnOnce() -> Result<T, E1>,
    E1: Debug,
    E: FnOnce(E1) -> Error,
{
    let start = Instant::now();

    tracing::trace!("Running db operation {}", info);

    let result = operation().map_err(|e| {
        tracing::error!("Query {} failed with error {:?}", info, e);
        error_map(e)
    });

    let duration = start.elapsed();
    if duration.as_millis() > SLOW_QUERY_THRESHOLD_MS {
        tracing::warn!("[SLOW QUERY] Took {} ms: {}", duration.as_millis(), info);
    }

    result
}

/// Run a database operation and log slow operations, it also converts and logs any error with a
/// given info for more context
#[inline(always)]
pub async fn run_db_operation<Fut, E, E1, T>(
    info: &str,
    operation: Fut,
    error_map: E,
) -> Result<T, Error>
where
    Fut: Future<Output = Result<T, E1>>,
    E1: Debug,
    E: FnOnce(E1) -> Error,
{
    let start = Instant::now();

    tracing::trace!("Running db operation {}", info);

    let result = operation.await.map_err(|e| {
        tracing::error!("Query {} failed with error {:?}", info, e);
        error_map(e)
    });

    let duration = start.elapsed();
    if duration.as_millis() > SLOW_QUERY_THRESHOLD_MS {
        tracing::warn!("[SLOW QUERY] Took {} ms: {}", duration.as_millis(), info);
    }

    result
}

/// One migration the runner is about to apply.
enum Step<'a, C>
where
    C: DatabaseExecutor,
{
    Sql(&'a str),
    Rust(Box<dyn RustMigration<C>>),
}

/// Migrates the SQL migrations generated by `build.rs` together with the migrations written in
/// Rust, interleaved by the numeric prefix they share.
///
/// The SQL list keeps the order `build.rs` gave it and is never re-sorted, so splicing the Rust
/// entries in cannot shift the order any existing database was migrated in.
///
/// The merge below uses plain loops rather than iterator adaptors: a closure over
/// `&&(&str, &str, &str)` here defeats the compiler's `Send` inference for every async caller that
/// spawns this future.
#[inline(always)]
pub async fn migrate<C>(
    conn: &C,
    db_prefix: &str,
    sql_migrations: &[(&str, &str, &str)],
    rust_migrations: Vec<RegisteredRustMigration<C>>,
) -> Result<(), Error>
where
    C: DatabaseExecutor + 'static,
{
    query(
        r#"
           CREATE TABLE IF NOT EXISTS migrations (
               name TEXT PRIMARY KEY,
               applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
           )
           "#,
    )?
    .execute(conn)
    .await?;

    let mut rust = Vec::new();

    for entry in rust_migrations {
        if entry.dialect.driver_name() == db_prefix {
            rust.push((migration_order_key(entry.name), entry.name, entry.migration));
        }
    }

    rust.reverse();

    let mut steps = Vec::new();

    for (prefix, name, sql_text) in sql_migrations {
        if !prefix.is_empty() && *prefix != db_prefix {
            continue;
        }

        let sql_key = migration_order_key(name);

        while !rust.is_empty() {
            let next = rust.len() - 1;

            if rust[next].0 >= sql_key {
                break;
            }

            let (_, rust_name, migration) = rust.remove(next);
            steps.push((rust_name, Step::Rust(migration)));
        }

        steps.push((name, Step::Sql(sql_text)));
    }

    while let Some((_, rust_name, migration)) = rust.pop() {
        steps.push((rust_name, Step::Rust(migration)));
    }

    for (name, step) in steps {
        if is_applied(conn, name).await? {
            continue;
        }

        match step {
            Step::Sql(sql_text) => query(sql_text)?.batch(conn).await?,
            Step::Rust(migration) => migration.apply(conn).await?,
        }

        record_applied(conn, name).await?;
    }

    Ok(())
}

/// The key `build.rs` sorts migrations by: the leading integer of the name. A name without one
/// sorts first, as it does there. The parse error carries nothing beyond "not a number", which is
/// what the fallback already encodes.
pub(crate) fn migration_order_key(name: &str) -> u64 {
    name.split('_')
        .next()
        .and_then(|prefix| prefix.parse().ok())
        .unwrap_or_default()
}

async fn is_applied<C>(conn: &C, name: &str) -> Result<bool, Error>
where
    C: DatabaseExecutor,
{
    Ok(query("SELECT name FROM migrations WHERE name = :name")?
        .bind("name", name)
        .pluck(conn)
        .await?
        .is_some())
}

async fn record_applied<C>(conn: &C, name: &str) -> Result<(), Error>
where
    C: DatabaseExecutor,
{
    query(r#"INSERT INTO migrations (name) VALUES (:name)"#)?
        .bind("name", name)
        .execute(conn)
        .await?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use async_trait::async_trait;

    use super::{migrate, migration_order_key};
    use crate::database::DatabaseExecutor;
    use crate::fake_executor::FakeExecutor;
    use crate::migration::{Dialect, RegisteredRustMigration, RustMigration};
    use crate::stmt::query;

    /// A Rust migration that only leaves a recognisable mark, so a test can see where in the order
    /// the runner placed it.
    #[derive(Debug)]
    struct Marker(&'static str);

    #[async_trait]
    impl<C> RustMigration<C> for Marker
    where
        C: DatabaseExecutor,
    {
        async fn apply(&self, conn: &C) -> Result<(), cdk_common::database::Error> {
            query(self.0)?.batch(conn).await
        }
    }

    const SQL: &[(&str, &str, &str)] = &[
        ("sqlite", "1_first.sql", "MARK first"),
        ("sqlite", "30_last.sql", "MARK last"),
        ("postgres", "20_other_dialect.sql", "MARK other_dialect"),
    ];

    fn rust_entry(dialect: Dialect, name: &'static str) -> RegisteredRustMigration<FakeExecutor> {
        RegisteredRustMigration {
            dialect,
            name,
            migration: Box::new(Marker(match name {
                "20_middle.rs" => "MARK middle",
                _ => "MARK unexpected",
            })),
        }
    }

    fn marks(conn: &FakeExecutor) -> Vec<String> {
        conn.executed()
            .into_iter()
            .filter(|sql| sql.starts_with("MARK "))
            .collect()
    }

    #[tokio::test]
    async fn a_rust_migration_runs_where_its_prefix_places_it() {
        let conn = FakeExecutor::default();

        migrate(
            &conn,
            "sqlite",
            SQL,
            vec![rust_entry(Dialect::Sqlite, "20_middle.rs")],
        )
        .await
        .expect("migrate");

        assert_eq!(marks(&conn), ["MARK first", "MARK middle", "MARK last"]);
    }

    #[tokio::test]
    async fn entries_for_another_dialect_are_left_alone() {
        let conn = FakeExecutor::default();

        migrate(
            &conn,
            "sqlite",
            SQL,
            vec![rust_entry(Dialect::Postgres, "20_middle.rs")],
        )
        .await
        .expect("migrate");

        assert_eq!(marks(&conn), ["MARK first", "MARK last"]);
        assert!(!conn.recorded_names().contains(&"20_middle.rs".to_owned()));
    }

    #[tokio::test]
    async fn an_already_recorded_rust_migration_is_skipped() {
        let conn = FakeExecutor::with_applied(&["20_middle.rs"]);

        migrate(
            &conn,
            "sqlite",
            SQL,
            vec![rust_entry(Dialect::Sqlite, "20_middle.rs")],
        )
        .await
        .expect("migrate");

        assert_eq!(marks(&conn), ["MARK first", "MARK last"]);
    }

    #[tokio::test]
    async fn every_applied_migration_is_recorded_under_its_own_name() {
        let conn = FakeExecutor::default();

        migrate(
            &conn,
            "sqlite",
            SQL,
            vec![rust_entry(Dialect::Sqlite, "20_middle.rs")],
        )
        .await
        .expect("migrate");

        assert_eq!(
            conn.recorded_names(),
            ["1_first.sql", "20_middle.rs", "30_last.sql"]
        );
    }

    #[test]
    fn order_key_matches_the_build_script() {
        assert_eq!(migration_order_key("1_initial.sql"), 1);
        assert_eq!(
            migration_order_key("20240612132920_init.sql"),
            20240612132920
        );
        assert_eq!(
            migration_order_key("20260902000000_mint_internal_id.rs"),
            20260902000000
        );
        assert!(
            migration_order_key("20260902000000_mint_internal_id.rs")
                > migration_order_key("20260811000000_add_proof_derivation_index.sql")
        );
    }

    #[test]
    fn order_key_of_a_nameless_prefix_sorts_first() {
        assert_eq!(migration_order_key("initial.sql"), 0);
    }
}
