-- Migration 011: give every mint an internal id and point rows at that id
--
-- A mint URL is a mutable attribute, not an identity: a mint that announces a
-- new endpoint (NUT-06 `urls`) is still the same mint. Keying rows on the URL
-- meant a move had to rewrite every table, and any table missed left rows
-- stranded under the old URL.

-- Rows could reference a mint URL that was never added. Give those a mint row
-- so nothing is stranded once the reference becomes an id.
INSERT INTO mint (mint_url, wallet_id)
SELECT DISTINCT mint_url, wallet_id
FROM (
    SELECT mint_url, wallet_id FROM keyset
    UNION SELECT mint_url, wallet_id FROM mint_quote
    UNION SELECT mint_url, wallet_id FROM melt_quote WHERE mint_url IS NOT NULL
    UNION SELECT mint_url, wallet_id FROM proof
    UNION SELECT mint_url, wallet_id FROM transactions
    UNION SELECT data::jsonb ->> 'mint_url', wallet_id FROM saga
        WHERE data::jsonb ? 'mint_url'
) AS referenced
WHERE mint_url IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM mint m
      WHERE m.mint_url = referenced.mint_url
        AND m.wallet_id = referenced.wallet_id
  );

ALTER TABLE mint ADD COLUMN IF NOT EXISTS mint_id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE mint ADD CONSTRAINT mint_mint_id_key UNIQUE (mint_id, wallet_id);

ALTER TABLE keyset ADD COLUMN IF NOT EXISTS mint_id BIGINT;
UPDATE keyset SET mint_id = m.mint_id FROM mint m
    WHERE m.mint_url = keyset.mint_url AND m.wallet_id = keyset.wallet_id;
ALTER TABLE keyset ALTER COLUMN mint_id SET NOT NULL;
DROP INDEX IF EXISTS idx_keyset_mint_url;
ALTER TABLE keyset DROP COLUMN mint_url;
ALTER TABLE keyset ADD CONSTRAINT keyset_mint_fkey
    FOREIGN KEY (mint_id, wallet_id) REFERENCES mint(mint_id, wallet_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_keyset_mint_id ON keyset(mint_id);

ALTER TABLE mint_quote ADD COLUMN IF NOT EXISTS mint_id BIGINT;
UPDATE mint_quote SET mint_id = m.mint_id FROM mint m
    WHERE m.mint_url = mint_quote.mint_url AND m.wallet_id = mint_quote.wallet_id;
ALTER TABLE mint_quote ALTER COLUMN mint_id SET NOT NULL;
DROP INDEX IF EXISTS idx_mint_quote_mint_url;
ALTER TABLE mint_quote DROP COLUMN mint_url;
ALTER TABLE mint_quote ADD CONSTRAINT mint_quote_mint_fkey
    FOREIGN KEY (mint_id, wallet_id) REFERENCES mint(mint_id, wallet_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_mint_quote_mint_id ON mint_quote(mint_id);

ALTER TABLE melt_quote ADD COLUMN IF NOT EXISTS mint_id BIGINT;
UPDATE melt_quote SET mint_id = m.mint_id FROM mint m
    WHERE m.mint_url = melt_quote.mint_url AND m.wallet_id = melt_quote.wallet_id;
ALTER TABLE melt_quote DROP COLUMN mint_url;
ALTER TABLE melt_quote ADD CONSTRAINT melt_quote_mint_fkey
    FOREIGN KEY (mint_id, wallet_id) REFERENCES mint(mint_id, wallet_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_melt_quote_mint_id ON melt_quote(mint_id);

ALTER TABLE proof ADD COLUMN IF NOT EXISTS mint_id BIGINT;
UPDATE proof SET mint_id = m.mint_id FROM mint m
    WHERE m.mint_url = proof.mint_url AND m.wallet_id = proof.wallet_id;
ALTER TABLE proof ALTER COLUMN mint_id SET NOT NULL;
DROP INDEX IF EXISTS idx_proof_mint_url;
ALTER TABLE proof DROP COLUMN mint_url;
ALTER TABLE proof ADD CONSTRAINT proof_mint_fkey
    FOREIGN KEY (mint_id, wallet_id) REFERENCES mint(mint_id, wallet_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_proof_mint_id ON proof(mint_id);

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS mint_id BIGINT;
UPDATE transactions SET mint_id = m.mint_id FROM mint m
    WHERE m.mint_url = transactions.mint_url AND m.wallet_id = transactions.wallet_id;
ALTER TABLE transactions ALTER COLUMN mint_id SET NOT NULL;
DROP INDEX IF EXISTS idx_transactions_mint_url;
ALTER TABLE transactions DROP COLUMN mint_url;
ALTER TABLE transactions ADD CONSTRAINT transactions_mint_fkey
    FOREIGN KEY (mint_id, wallet_id) REFERENCES mint(mint_id, wallet_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_transactions_mint_id ON transactions(mint_id);

-- A saga carried its mint reference inside its serialized payload; it moves to
-- a column so the payload never goes stale.
ALTER TABLE saga ADD COLUMN IF NOT EXISTS mint_id BIGINT;
UPDATE saga SET mint_id = m.mint_id FROM mint m
    WHERE m.wallet_id = saga.wallet_id AND m.mint_url = saga.data::jsonb ->> 'mint_url';
ALTER TABLE saga ALTER COLUMN mint_id SET NOT NULL;
ALTER TABLE saga ADD CONSTRAINT saga_mint_fkey
    FOREIGN KEY (mint_id, wallet_id) REFERENCES mint(mint_id, wallet_id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_saga_mint_id ON saga(mint_id);
UPDATE saga SET data = (data::jsonb - 'mint_url')::text;

CREATE OR REPLACE FUNCTION update_proofs_atomic(
    p_proofs_to_add JSONB DEFAULT '[]'::JSONB,
    p_ys_to_remove JSONB DEFAULT '[]'::JSONB
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
SET search_path = ''
AS $body$
    WITH
    removed AS (
        DELETE FROM public.proof
        WHERE wallet_id = public.get_current_wallet_id()
          AND y = ANY(SELECT pg_catalog.jsonb_array_elements_text(p_ys_to_remove))
        RETURNING y
    ),
    inserted AS (
        INSERT INTO public.proof AS existing (
            y, wallet_id, mint_id, state, spending_condition, unit, amount,
            keyset_id, secret, c, witness, dleq_e, dleq_s, dleq_r,
            used_by_operation, created_by_operation, p2pk_e, derivation_index
        )
        SELECT
            p->>'y',
            public.get_current_wallet_id(),
            (p->>'mint_id')::BIGINT,
            p->>'state',
            p->>'spending_condition',
            p->>'unit',
            (p->>'amount')::BIGINT,
            p->>'keyset_id',
            p->>'secret',
            p->>'c',
            p->>'witness',
            p->>'dleq_e',
            p->>'dleq_s',
            p->>'dleq_r',
            p->>'used_by_operation',
            p->>'created_by_operation',
            p->>'p2pk_e',
            (p->>'derivation_index')::INTEGER
        FROM pg_catalog.jsonb_array_elements(p_proofs_to_add) AS p
        ON CONFLICT (y, wallet_id) DO UPDATE SET
            mint_id = EXCLUDED.mint_id,
            state = EXCLUDED.state,
            spending_condition = EXCLUDED.spending_condition,
            unit = EXCLUDED.unit,
            amount = EXCLUDED.amount,
            keyset_id = EXCLUDED.keyset_id,
            secret = EXCLUDED.secret,
            c = EXCLUDED.c,
            witness = EXCLUDED.witness,
            dleq_e = EXCLUDED.dleq_e,
            dleq_s = EXCLUDED.dleq_s,
            dleq_r = EXCLUDED.dleq_r,
            used_by_operation = EXCLUDED.used_by_operation,
            created_by_operation = EXCLUDED.created_by_operation,
            p2pk_e = EXCLUDED.p2pk_e,
            derivation_index = COALESCE(
                EXCLUDED.derivation_index,
                existing.derivation_index
            )
        RETURNING y
    )
    SELECT pg_catalog.jsonb_build_object(
        'added',   (SELECT count(*) FROM inserted),
        'removed', (SELECT count(*) FROM removed)
    )
$body$;

INSERT INTO schema_info (key, value) VALUES ('schema_version', '11')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
