"""Python bindings for the Cashu Development Kit wallet.

The `cdk_ffi` module beside this file is generated by uniffi-bindgen at build
time and is not checked in; it loads the native library from this same package
directory.
"""

from .cdk_ffi import *  # noqa: F401,F403
