[package]
name = "cdk-bdk"
version = "0.1.0"
edition = "2021"
authors = ["CDK Developers"]
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true # MSRV
license.workspace = true
description = "BDK on chain wallet for mint"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bitcoin = "0.32.0"
bdk_chain = "0.16.0"
bdk_wallet = { version = "1.0.0-alpha.13", default-features = false, features = ["keys-bip39"] }
bdk_esplora = { version = "0.15.0", default-features = false, features = ["std", "async-https"] }
bdk_file_store = "0.13.0"
cdk = { workspace = true, default-features = false, features = ["mint"] }
futures.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
uuid.workspace = true
