name: Close inactive issues and PRs
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 21
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 21 days since being marked as stale."
          days-before-pr-stale: 60
          days-before-pr-close: 21
          stale-pr-label: "stale"
          stale-pr-message: "This PR is stale because it has been open for 60 days with no activity."
          close-pr-message: "This PR was closed because it has been inactive for 21 days since being marked as stale."
          exempt-issue-labels: "keep-open"
          exempt-pr-labels: "keep-open"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
