require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |spec|
  spec.name         = "CashuNative"
  spec.version      = package["version"]
  spec.summary      = package["description"]
  spec.homepage     = "https://github.com/cashubtc/cdk"
  spec.license      = package["license"]
  spec.authors      = "CDK Developers"
  spec.platforms    = { :ios => "13.4" }
  spec.source       = { :git => "https://github.com/cashubtc/cdk.git", :tag => "v#{spec.version}" }

  # Hand-written: nothing. Everything below is generated by
  # `just nitro-bindings` and `just nitro-ios`, and is not in git.
  spec.source_files = "cpp/generated/**/*.{hpp,cpp}"
  spec.vendored_frameworks = "ios/generated/cashu_ffi.xcframework"

  spec.pod_target_xcconfig = {
    "HEADER_SEARCH_PATHS" => "\"$(PODS_TARGET_SRCROOT)/cpp/generated\"",
  }

  spec.dependency "React-Core"

  load File.join(__dir__, "nitrogen/generated/ios/CashuNative+autolinking.rb")
  add_nitrogen_files(spec)
end
