require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name         = 'cashu-dev-kit'
  s.version      = package['version']
  s.summary      = package['description']
  s.homepage     = 'https://github.com/cashubtc/cdk'
  s.license      = package['license']
  s.authors      = 'Cashu Dev Kit Contributors'
  s.source       = { git: 'https://github.com/cashubtc/cdk.git', tag: s.version.to_s }
  s.platforms    = { ios: '13.0' }

  # Our handwritten bridge and the C FFI header.
  s.source_files = 'cpp/**/*.{h,hpp,cpp}'

  # Pull in everything Nitrogen generated: the spec sources, the autolinking
  # registration (CashuDevKitAutolinking.mm), the public/private header setup,
  # the NitroModules dependency, and the C++20 / Swift-interop xcconfig. This
  # is authoritative and regenerated by `npm run codegen`.
  load 'nitrogen/generated/ios/CashuDevKit+autolinking.rb'
  add_nitrogen_files(s)

  # Link against pre-built CdkNitro XCFramework. CocoaPods links the vendored
  # framework's static library automatically, so no explicit -lcdk_nitro flag
  # is needed (and adding one would fail, since the archive lives inside the
  # XCFramework rather than on the linker search path).
  s.vendored_frameworks = 'ios/Frameworks/CdkNitro.xcframework'

  # The handwritten cpp/ dir is not covered by the generated header paths.
  s.pod_target_xcconfig = (s.attributes_hash['pod_target_xcconfig'] || {}).merge({
    'HEADER_SEARCH_PATHS' => '"$(PODS_TARGET_SRCROOT)/cpp"',
  })
end
